# Generated by Django 4.2.13 on 2024-09-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datas', '0015_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datamodel',
            name='image',
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
